### ISSUE TITLE
Console error: Uncaught TypeError - this.app.customCSS.applyCSS is not a function

### ISSUE THREAD

**Issue by lunule** [nothingislost/obsidian-workspaces-plus#107]
**The console is displaying this error:**

``` js
app.js:1 Uncaught TypeError: this.app.customCss.applyCss is not a function
    at WorkspacesPlus.applySettings (plugin:workspaces-plus:4528:28)
    at WorkspacesPlus.onWorkspaceLoad (plugin:workspaces-plus:4217:22)
    at e.tryTrigger (app.js:1:725925)
    at e.trigger (app.js:1:725858)
    at t.trigger (app.js:1:2234949)
    at e.loadWorkspace (plugin:workspaces-plus:4620:40)
    at e.wrapper [as loadWorkspace] (plugin:workspaces-plus:3158:24)
    at WorkspacesPlusPluginWorkspaceModal.loadWorkspace (plugin:workspaces-plus:2813:30)
    at WorkspacesPlusPluginWorkspaceModal.onChooseItem (plugin:workspaces-plus:2807:18)
    at t.onChooseSuggestion (app.js:1:1564140)
```

**To Reproduce**

- Open Obsidian 
   - with the plugin enabled, and
   - with the `custom` option enabled at `Appearance > CSS Snippets`
- Open console to monitor errors.

**Expected behavior**

No errors in console.

**Screenshot:**

![image](https://github.com/nothingislost/obsidian-workspaces-plus/assets/190486/c956cc88-e2b9-4ece-b251-521a5a3044a8)

**Desktop (please complete the following information):**

OS: Windows 11
Obsidian desktop app
Version 1.6.3
ASUS notebook

Additional context
Workspaces Plus v0.3.3

**Comment by ksdavidc** [comment]
Me too on a mac

SYSTEM INFO:
	Obsidian version: 1.12.7
	Installer version: 1.12.7
	Operating system: Darwin Kernel Version 
worskpaces plus 0.3.3
